import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/home.module.css'
import { useEffect } from 'react'
const inter = Inter({ subsets: ['latin'] })


export default function Home() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.container}>
          {boardState.kubes.map((k, idx) => {
            return (<div key={`${k.color}-${k.number}-${idx}`} className={styles.kube} style={{ color: k.color }}>
              {k.number}
            </div>)
          })}
        </div>
      </main>
    </>
  )
}
